# run from build directory
# sudo docker build --tag jasondellaluce/scapvsock-server -f ./../userspace/libscap/examples/00-vsockforward/Dockerfile.server .

FROM ubuntu:24.04 AS runner

ENV HOST_ROOT /host
ENV HOME /root

COPY /libscap/examples/00-vsockforward/scap-vsockforward-srv /usr/bin/scap-vsock-server

CMD ["/usr/bin/scap-vsock-server"]
